<script>
    import { goto } from "$app/navigation";
    import fetcher from "$lib/fetcher";
    import { applicationStore } from "$lib/stores/applicationStore";
    import { onMount } from "svelte";
    import Swal from "sweetalert2";

    let formData = $state({
        email: localStorage.getItem("pending_login_email") || "",
        loading: false,
        otp: ["", "", "", "", "", ""],
    });

    async function verifyOTP() {
        if (formData.loading) return;

        try {
            formData.loading = true;

            const finalOTP = formData.otp.join("");

            if (finalOTP.length !== 6 || /\D/.test(finalOTP)) {
                Swal.fire({
                    icon: "error",
                    title: "OTP Tidak Valid",
                    text: "Kode OTP harus 6 digit angka.",
                });
                return;
            }

            const URLVerify = `${applicationStore.urlPlatformConsole}/login/mfa/verify`;

            const payload = {
                email: formData.email,
                otp: finalOTP,
            };

            const rst = await fetcher(fetch, URLVerify, {
                method: "POST",
                body: JSON.stringify(payload),
            });

            if (rst.accessToken) {
                Swal.fire({
                    icon: "success",
                    title: "OTP Berhasil Diverifikasi",
                    text: "Login berhasil. Mengarahkan ke dashboard...",
                    timer: 1200,
                    showConfirmButton: false,
                }).then(() => {
                    goto("/");
                });
            } else {
                Swal.fire({
                    icon: "error",
                    title: "OTP Salah",
                    text:
                        rst.message ||
                        "Kode OTP yang Anda masukkan tidak sesuai.",
                });
            }
        } catch (err) {
            Swal.fire({
                icon: "error",
                title: "OTP Salah",
                text:
                    err?.message || "Kode OTP yang Anda masukkan tidak sesuai.",
                confirmButtonText: "OK",
            });
        } finally {
            formData.loading = false;
        }
    }

    let otp = $state(["", "", "", "", "", ""]);
    let otpBoxes = [];

    function focusBox(idx) {
        if (idx < 0 || idx >= otpBoxes.length) return;
        otpBoxes[idx]?.focus();
        otpBoxes[idx]?.select();
    }

    function handleInput(e, idx, otpLength) {
        const value = e.target.value.replace(/\D/g, "");

        otp[idx] = value;

        // kalau isi & bukan input terakhir → pindah fokus
        if (value && idx < otpLength - 1) {
            otpBoxes[idx + 1]?.focus();
        }
    }

    function handleKeydown(e, idx) {
        if (e.key === "Backspace") {
            if (!otp[idx] && idx > 0) {
                focusBox(idx - 1);
            }
        } else if (e.key === "ArrowLeft") {
            focusBox(idx - 1);
        } else if (e.key === "ArrowRight") {
            focusBox(idx + 1);
        } else if (e.key.length === 1 && /\D/.test(e.key)) {
            e.preventDefault();
        }
    }

    onMount(() => {
        if (!localStorage.getItem("pending_login_email")) {
            goto("/login");
        }

        focusBox(0);
    });
</script>

<div
    class="public d-flex flex-column justify-content-center align-items-center"
>
    <div class="bottom-left-overlay"></div>
    <div class="otp-container">
        <div class="otp-card text-center">

            <img src="img/auth/shield.png" alt="logo" class="mb-4" />
            <h5 class="text-center mb-1">Enter Your Authentication Code</h5>

            <p class="mfa-step-detail text-center">
                Enter the 6-digit code generated by your Google Authenticator app.
            </p>

            <form
                onsubmit={() => {
                    verifyOTP();
                }}
            >
                <div class="otp-wrapper col-12 text-center gap-2">
                    {#each otp as value, idx (idx)}
                        <input
                            class="otp-box mx-1"
                            maxlength="1"
                            autocomplete="one-time-code"
                            bind:this={otpBoxes[idx]}
                            bind:value={formData.otp[idx]}
                            oninput={(e) => handleInput(e, idx, 6)}
                            onkeydown={(e) => handleKeydown(e, idx)}
                            onpaste={(e) => handlePaste(e, idx)}
                        />
                    {/each}
                </div>

                <button
                    type="submit"
                    class="otp-btn btn btn-gradient-primary my-2 mt-4"
                    disabled={formData.loading ||
                        formData.otp.join("").length !== 6}
                    >{#if !formData.loading}Enter{:else}
                        <span class="spinner-border spinner-border-sm me-1"
                        ></span>Please wait ...
                    {/if}</button
                >
                <div class="my-3 text-center">
                    <p>
                        <a href="/login" class="text-muted text-decoration-none"
                            >Kembali ke login</a
                        >
                    </p>
                </div>
            </form>
        </div>
    </div>
    <div class="top-right-overlay"></div>
</div>

<style lang="scss">
    .otp-container {
        position: relative;
        z-index: 10;
    }

    .otp-card {
        width: 560px;
        padding: 374px;
        background: #fff;
        border-radius: 24px;
        border: 1px solid #e0e0e0;
        padding: 26px 36px;
        box-shadow: 0 10px 40px rgba(0, 0, 0, 0.1);
        gap: 32px;
    }

    .otp-title {
        font-size: 20px;
        font-weight: 700;
        color: #111;
    }

    .otp-subtitle {
        color: #777;
        font-size: 14px;
    }

    .otp-btn {
        width: 488px;
        height: 42px;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .otp-btn:hover {
        opacity: 0.9;
    }

    .otp-box {
        width: 50px;
        height: 55px;
        border-radius: 10px;
        border: 1px solid #ddd;
        text-align: center;
        font-size: 22px;
        font-weight: bold;
    }
</style>
